drivers: thermal: msmSimple: Temporary fix missing qpnp-adc
Fixed by adding from our sdm710 source
 error: 'linux/qpnp/qpnp-adc.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: negrroo <mohammedaelnaggar1@gmail.com>